image:
  - Visual Studio 2017

environment:
  matrix:
    - BUILD_SHARED_LIBS: OFF
      WITH_EXTRA_TESTS: OFF

    - BUILD_SHARED_LIBS: OFF
      WITH_EXTRA_TESTS: ON

    - BUILD_SHARED_LIBS: ON
      WITH_EXTRA_TESTS: OFF

    - BUILD_SHARED_LIBS: ON
      WITH_EXTRA_TESTS: ON

build_script:
  - cmd: git clone https://github.com/stefanosoffia/googletest

  - cmd: cd googletest/

  - cmd: git checkout -b test e1b7c7687c37af2eefe93d3284516e3dfe5fce2c

  - cmd: cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX=%cd%\_install -G "Visual Studio 15 2017" -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -Dgtest_force_shared_crt=ON
  - cmd: cmake --build _builds --config Release --target install

  - cmd: cd C:\projects\gtest-conflict

  - cmd: cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX=C:\projects\gtest-conflict\googletest\_install -G "Visual Studio 15 2017" -DWITH_EXTRA_TESTS=%WITH_EXTRA_TESTS%
  - cmd: cmake --build _builds --config Release

  - cmd: cd _builds
  - cmd: ctest -VV -C Release
